"""initial_schema_all_tables

Revision ID: c9005076345a
Revises: 
Create Date: 2026-04-20 18:09:39.354328

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c9005076345a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rbi_macro_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upload_batch_id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('repo_rate', sa.Float(), nullable=True),
    sa.Column('credit_growth', sa.Float(), nullable=True),
    sa.Column('liquidity_indicator', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('jti', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('jti')
    )
    op.create_index('ix_revoked_tokens_jti', 'revoked_tokens', ['jti'], unique=False)
    op.create_table('score_snapshots',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('stock_symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('composite_score', sa.Float(), nullable=False),
    sa.Column('signal', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('position_size', sa.Float(), nullable=False),
    sa.Column('computation_timestamp', sa.DateTime(), nullable=False),
    sa.Column('kite_snapshot_ts', sa.DateTime(), nullable=False),
    sa.Column('screener_csv_ts', sa.DateTime(), nullable=False),
    sa.Column('rbi_csv_ts', sa.DateTime(), nullable=False),
    sa.Column('factor_breakdown', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_score_snapshots_stock_symbol', 'score_snapshots', ['stock_symbol'], unique=False)
    op.create_table('screener_data',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('upload_batch_id', sa.Uuid(), nullable=False),
    sa.Column('stock_symbol', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('pe_ratio', sa.Float(), nullable=True),
    sa.Column('pb_ratio', sa.Float(), nullable=True),
    sa.Column('roe', sa.Float(), nullable=True),
    sa.Column('roce', sa.Float(), nullable=True),
    sa.Column('debt_to_equity', sa.Float(), nullable=True),
    sa.Column('current_ratio', sa.Float(), nullable=True),
    sa.Column('sales_growth', sa.Float(), nullable=True),
    sa.Column('profit_growth', sa.Float(), nullable=True),
    sa.Column('eps', sa.Float(), nullable=True),
    sa.Column('dividend_yield', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('screener_data')
    op.drop_index('ix_score_snapshots_stock_symbol', table_name='score_snapshots')
    op.drop_table('score_snapshots')
    op.drop_index('ix_revoked_tokens_jti', table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_table('rbi_macro_data')
    # ### end Alembic commands ###
